### ISSUE TITLE
Various errors in Error Reporting

### ISSUE THREAD

**Issue by jiang95-dev** [GoogleCloudPlatform/cloud-ops-sandbox#386] opened 2020-08-25 21:47 UTC
I found many reported bug in my Error Reporting page.
![image](https://user-images.githubusercontent.com/19853208/91231323-e27b8f80-e6e1-11ea-9e74-3815cfe1d8f8.png)
The following are details:
![image](https://user-images.githubusercontent.com/19853208/91231155-a3e5d500-e6e1-11ea-9360-857ac22e8346.png)
![image](https://user-images.githubusercontent.com/19853208/91231121-96304f80-e6e1-11ea-805a-3583d13ee96e.png)
![image](https://user-images.githubusercontent.com/19853208/91231204-b52ee180-e6e1-11ea-8916-9ca8371872e3.png)
![image](https://user-images.githubusercontent.com/19853208/91231235-c11aa380-e6e1-11ea-9b93-2e9bb03024b4.png)
![image](https://user-images.githubusercontent.com/19853208/91231264-cd9efc00-e6e1-11ea-9854-a933c29948f8.png)

**Comment by simonz130** [comment] 2020-08-26 00:18
Trace issue is a duplicate of #372

**Closed** 2020-09-11 18:12 UTC
Labels: priority: p2, type: bug
