### ISSUE TITLE
Add build-cop bot to Sandbox repo

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#553] opened 2020-10-30 17:13 UTC
Adding [build-cop bot](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop) will allow automated creation/closure of bugs associated with failed CI runs.

**Comment by Daniel-Sanche** [comment] 2020-11-09 21:47
It looks like buildcop requires us to generate xUnit XML files as output from our tests. This seems like it could be a pretty big change

If we wanted to use Build-cop, I'd probably suggest just moving all our tests onto kokoro. It would probably be a similar amount of work, and that would give us full compatibility with other DPE tools

**Comment by simonz130** [comment] 2020-11-10 07:03
Can we reuse existing test runners that output xUnit XML? Like this? https://pypi.org/project/unittest-xml-reporting/
How much effort would it be?

**Comment by Daniel-Sanche** [comment] 2020-11-10 17:59
We could possibly use those for the monitoring/integration tests. The problem is that a lot of our tests aren't formal unit tests. I don't think we'd be able to capture our installation logs or build/smoke tests in that way. It seems like we'd be the first to use buildcop for GitHub Actions too, so we may run into some unknown problems getting it to work

It looks like it should be possible, but it'll be more work than just enabling the bot. So we might want to discuss how much time we want to dedicate to it, and decide whether we want to change this repo to kokoro to make integrations like this easier going forward

**Comment by simonz130** [comment] 2021-04-08 21:21
Moving this issue to @Ayelet41 to take a look as part of moving CI to kokoro

**Comment by arbrown** [comment] 2022-08-10 18:49
@daniel-sanche - DO you think we can safely close this?

**Comment by daniel-sanche** [comment] 2022-08-10 19:10
Yeah, I think it's probably out of scope

**Closed by daniel-sanche** 2022-08-10 19:10 UTC
Labels: type: process, priority: p3, lang: yaml
