### ISSUE TITLE
Error creating AlertPolicy

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-ops-sandbox#414] opened 2020-08-29 02:29 UTC
When creating alerting policy as part of monitoring provisioning, I get this:
![image](https://user-images.githubusercontent.com/32641282/91626503-81afb980-e964-11ea-9fd3-d582ea517f81.png)

This is when using google.com account, but not sure if it's unique to this usecase.

**Comment by nicklin37** [comment] 2020-08-31 17:01
Could I get another googler @Daniel-Sanche or @nicoleczhu to test this out too? I was unable to reproduce for non-google accounts. From a Terraform perspective this is what we're doing: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/b2783aa4eb62bfc7c88e1e357731e6cdfb30ac6f/terraform/monitoring/01_uptime_checks.tf#L64 which doesn't seem like it should raise only a 404.

**Comment by Daniel-Sanche** [comment] 2020-09-08 18:26
Hmm I haven't been able to reproduce this. It could be a race condition? Is there a way to put that step in a retry loop until the pubsub channel is ready?

**Comment by nicklin37** [comment] 2020-09-11 21:31
Hm of all the sandboxes we've created recently I haven't seen this issue at all which makes me think it's a very specific edge case as to what's happening? there isn't any Terraform mechanisms to deal with race conditions since it orders the resources to avoid them most of the time. I'm not too sure if this is an issue we still need to address?

**Comment by nicklin37** [comment] 2020-09-18 23:17
In my opinion this issue can be closed since it seems to have been a random error without anything we can really do about it - but I'll reassign Simon in the case there is something we find out we can do about it.

**Comment by nicoleczhu** [comment] 2020-10-07 20:33
This issue happens for me 1/3 times. More logs here: https://paste.googleplex.com/5788325278384128

**Comment by Ayelet41** [comment] 2021-05-24 10:46
@nicoleczhu @simonz130 is this issue still relevant? I was not able to reproduce it.

**Comment by Ayelet41** [comment] 2021-06-16 13:07
@simonz130 I couldn't reproduce it, are you still encounter this issue?

**Comment by Ayelet41** [comment] 2021-06-24 12:38
Happened again on mater(not consistent). Rerun seems to solve the problem.

**Closed** 2022-05-25 22:59 UTC
Labels: type: feature request, priority: p2
