### ISSUE TITLE
Cannot provision load balancer

### ISSUE THREAD

**Issue by yuriatgoogle** [GoogleCloudPlatform/cloud-ops-sandbox#392] opened 2020-08-26 15:34 UTC
Error on the frontend-external service:

```Error syncing load balancer: failed to ensure load balancer: failed to create forwarding rule for load balancer (ab641cd3fdbff47ee9248bbee04e7f01(default/frontend-external)): googleapi: Error 412: Constraint constraints/compute.restrictLoadBalancerCreationForTypes violated for projects/stackdriver-sandbox-3475767433. Forwarding Rule projects/stackdriver-sandbox-3475767433/regions/us-central1/forwardingRules/ab641cd3fdbff47ee9248bbee04e7f01 of type EXTERNAL_NETWORK_TCP_UDP is not allowed., conditionNotMet```

This is in the google.com org.

![image](https://user-images.githubusercontent.com/26609620/91324475-fa512300-e776-11ea-8c33-c4d3debcb365.png)

**Comment by yuriatgoogle** [comment] 2020-08-26 15:37
Creation seems to hang from there:
```
Apply complete! Resources: 13 added, 0 changed, 0 destroyed.
Fetching cluster endpoint and auth data.
kubeconfig entry generated for stackdriver-sandbox.
Retrieving the external IP address of the application...
Could not retrieve external IP... skipping monitoring configuration.
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
Waiting for Hipster Shop endpoint...
```

**Comment by nicklin37** [comment] 2020-08-26 19:02
Thanks Yuri! This is the same issue as #369 caused by changes in the policies for Googlers. We're actively working on resolving this issue!

**Comment by yuriatgoogle** [comment] 2020-08-26 19:54
Thank you very much for looking into this, much appreciated.

**Closed** 2020-08-31 18:40 UTC
Labels: priority: p2, type: bug
